import React from "react";

export interface TokenGroup {
  title: string;
  description: string;
  icon: React.ReactNode;
  tokens: {
    key: string;
    label: string;
    type: "color" | "number" | "string" | "select";
    description?: string;
    options?: { label: string; value: string | number }[];
    min?: number;
    max?: number;
    step?: number;
    unit?: string;
  }[];
}

export interface ComponentGroup {
  title: string;
  description: string;
  component: string;
  properties: {
    key: string;
    label: string;
    type: "color" | "number" | "string" | "select";
    description?: string;
    options?: { label: string; value: string | number }[];
    min?: number;
    max?: number;
    step?: number;
    unit?: string;
  }[];
}

export const useThemeConfiguration = () => {
  const tokenGroups: TokenGroup[] = [
    {
      title: "Primary Colors",
      description: "Main brand colors used throughout the interface",
      icon: "🎨",
      tokens: [
        {
          key: "colorPrimary",
          label: "Primary Color",
          type: "color",
          description:
            "Main brand color used for primary actions and highlights",
        },
        {
          key: "colorSuccess",
          label: "Success Color",
          type: "color",
          description: "Color used for success states and positive feedback",
        },
        {
          key: "colorWarning",
          label: "Warning Color",
          type: "color",
          description: "Color used for warning states and caution indicators",
        },
        {
          key: "colorError",
          label: "Error Color",
          type: "color",
          description: "Color used for error states and destructive actions",
        },
        {
          key: "colorInfo",
          label: "Info Color",
          type: "color",
          description:
            "Color used for informational content and neutral actions",
        },
      ],
    },
    {
      title: "Typography",
      description: "Font settings and text appearance",
      icon: "📝",
      tokens: [
        {
          key: "fontFamily",
          label: "Font Family",
          type: "select",
          description: "Primary font family for all text content",
          options: [
            {
              label: "System Default",
              value:
                "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
            },
            { label: "Inter", value: "'Inter', sans-serif" },
            { label: "Roboto", value: "'Roboto', sans-serif" },
            { label: "Open Sans", value: "'Open Sans', sans-serif" },
            { label: "Poppins", value: "'Poppins', sans-serif" },
            { label: "Montserrat", value: "'Montserrat', sans-serif" },
          ],
        },
        {
          key: "fontSize",
          label: "Base Font Size",
          type: "number",
          description: "Base font size for body text",
          min: 10,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "lineHeight",
          label: "Line Height",
          type: "number",
          description: "Default line height for text content",
          min: 1,
          max: 2.5,
          step: 0.1,
        },
      ],
    },
    {
      title: "Background Colors",
      description: "Background colors for different states and contexts",
      icon: "🌈",
      tokens: [
        {
          key: "colorBgBase",
          label: "Base Background",
          type: "color",
          description: "Primary background color for the application",
        },
        {
          key: "colorBgContainer",
          label: "Container Background",
          type: "color",
          description: "Background color for containers and cards",
        },
        {
          key: "colorBgElevated",
          label: "Elevated Background",
          type: "color",
          description: "Background color for elevated elements like modals",
        },
        {
          key: "colorBgLayout",
          label: "Layout Background",
          type: "color",
          description: "Background color for layout areas",
        },
        {
          key: "colorBgSpotlight",
          label: "Spotlight Background",
          type: "color",
          description: "Background color for highlighted content",
        },
      ],
    },
    {
      title: "Border & Line Colors",
      description: "Border and divider line colors",
      icon: "📏",
      tokens: [
        {
          key: "colorBorder",
          label: "Default Border",
          type: "color",
          description: "Default border color for components",
        },
        {
          key: "colorBorderSecondary",
          label: "Secondary Border",
          type: "color",
          description: "Secondary border color for subtle divisions",
        },
        {
          key: "colorSplit",
          label: "Split Line Color",
          type: "color",
          description: "Color for divider lines and separators",
        },
        {
          key: "wireframe",
          label: "Wireframe Mode",
          type: "select",
          description: "Enable wireframe styling for debugging",
          options: [
            { label: "Disabled", value: "false" },
            { label: "Enabled", value: "true" },
          ],
        },
      ],
    },
    {
      title: "Text Colors",
      description: "Text color hierarchy and states",
      icon: "✏️",
      tokens: [
        {
          key: "colorText",
          label: "Primary Text",
          type: "color",
          description: "Primary text color for body content",
        },
        {
          key: "colorTextSecondary",
          label: "Secondary Text",
          type: "color",
          description: "Secondary text color for less important content",
        },
        {
          key: "colorTextTertiary",
          label: "Tertiary Text",
          type: "color",
          description: "Tertiary text color for subtle text",
        },
        {
          key: "colorTextQuaternary",
          label: "Quaternary Text",
          type: "color",
          description: "Lightest text color for placeholders",
        },
        {
          key: "colorTextDisabled",
          label: "Disabled Text",
          type: "color",
          description: "Text color for disabled elements",
        },
      ],
    },
    {
      title: "Size & Spacing",
      description: "Component sizes and spacing controls",
      icon: "📐",
      tokens: [
        {
          key: "controlHeight",
          label: "Control Height",
          type: "number",
          description: "Default height for form controls",
          min: 24,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "controlHeightSM",
          label: "Small Control Height",
          type: "number",
          description: "Height for small form controls",
          min: 16,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "controlHeightLG",
          label: "Large Control Height",
          type: "number",
          description: "Height for large form controls",
          min: 32,
          max: 56,
          step: 2,
          unit: "px",
        },
        {
          key: "padding",
          label: "Default Padding",
          type: "number",
          description: "Default padding for components",
          min: 8,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingSM",
          label: "Small Padding",
          type: "number",
          description: "Small padding for compact components",
          min: 4,
          max: 20,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingLG",
          label: "Large Padding",
          type: "number",
          description: "Large padding for spacious components",
          min: 16,
          max: 48,
          step: 4,
          unit: "px",
        },
        {
          key: "margin",
          label: "Default Margin",
          type: "number",
          description: "Default margin for components",
          min: 8,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "marginSM",
          label: "Small Margin",
          type: "number",
          description: "Small margin for compact layouts",
          min: 4,
          max: 20,
          step: 2,
          unit: "px",
        },
        {
          key: "marginLG",
          label: "Large Margin",
          type: "number",
          description: "Large margin for spacious layouts",
          min: 16,
          max: 48,
          step: 4,
          unit: "px",
        },
      ],
    },
    {
      title: "Motion & Animation",
      description: "Animation duration and easing settings",
      icon: "⚡",
      tokens: [
        {
          key: "motionDurationFast",
          label: "Fast Duration",
          type: "string",
          description: "Duration for fast animations",
        },
        {
          key: "motionDurationMid",
          label: "Medium Duration",
          type: "string",
          description: "Duration for medium speed animations",
        },
        {
          key: "motionDurationSlow",
          label: "Slow Duration",
          type: "string",
          description: "Duration for slow animations",
        },
        {
          key: "motionEaseOutCirc",
          label: "Ease Out Circular",
          type: "string",
          description: "Circular ease-out animation curve",
        },
        {
          key: "motionEaseInOutCirc",
          label: "Ease In-Out Circular",
          type: "string",
          description: "Circular ease-in-out animation curve",
        },
      ],
    },
    {
      title: "Shadow & Elevation",
      description: "Box shadow settings for depth and elevation",
      icon: "🌑",
      tokens: [
        {
          key: "boxShadow",
          label: "Primary Shadow",
          type: "string",
          description: "Primary box shadow for elevated elements",
        },
        {
          key: "boxShadowSecondary",
          label: "Secondary Shadow",
          type: "string",
          description: "Secondary box shadow for subtle elevation",
        },
        {
          key: "boxShadowTertiary",
          label: "Tertiary Shadow",
          type: "string",
          description: "Tertiary box shadow for minimal elevation",
        },
        {
          key: "boxShadowPopover",
          label: "Popover Shadow",
          type: "string",
          description: "Box shadow for popovers and floating elements",
        },
        {
          key: "boxShadowDrawer",
          label: "Drawer Shadow",
          type: "string",
          description: "Box shadow for drawer panels",
        },
        {
          key: "boxShadowModal",
          label: "Modal Shadow",
          type: "string",
          description: "Box shadow for modal dialogs",
        },
      ],
    },
    {
      title: "Z-Index Layers",
      description: "Stacking order for overlapping elements",
      icon: "📚",
      tokens: [
        {
          key: "zIndexBase",
          label: "Base Z-Index",
          type: "number",
          description: "Base z-index for normal elements",
          min: 0,
          max: 10,
          step: 1,
        },
        {
          key: "zIndexPopupBase",
          label: "Popup Base Z-Index",
          type: "number",
          description: "Base z-index for popup elements",
          min: 1000,
          max: 2000,
          step: 10,
        },
        {
          key: "zIndexPopover",
          label: "Popover Z-Index",
          type: "number",
          description: "Z-index for popover elements",
          min: 1000,
          max: 2000,
          step: 10,
        },
        {
          key: "zIndexModal",
          label: "Modal Z-Index",
          type: "number",
          description: "Z-index for modal dialogs",
          min: 1000,
          max: 2000,
          step: 10,
        },
        {
          key: "zIndexDrawer",
          label: "Drawer Z-Index",
          type: "number",
          description: "Z-index for drawer panels",
          min: 1000,
          max: 2000,
          step: 10,
        },
      ],
    },
    {
      title: "Border Radius",
      description: "Border radius settings for different component sizes",
      icon: "🔲",
      tokens: [
        {
          key: "borderRadiusXS",
          label: "Extra Small Radius",
          type: "number",
          description: "Border radius for extra small components",
          min: 0,
          max: 8,
          step: 1,
          unit: "px",
        },
        {
          key: "borderRadiusSM",
          label: "Small Radius",
          type: "number",
          description: "Border radius for small components",
          min: 0,
          max: 12,
          step: 1,
          unit: "px",
        },
        {
          key: "borderRadiusLG",
          label: "Large Radius",
          type: "number",
          description: "Border radius for large components",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "borderRadiusOuter",
          label: "Outer Radius",
          type: "number",
          description: "Border radius for outer container elements",
          min: 0,
          max: 24,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Font Sizes",
      description: "Typography size hierarchy",
      icon: "🔤",
      tokens: [
        {
          key: "fontSizeSM",
          label: "Small Font Size",
          type: "number",
          description: "Small font size for secondary text",
          min: 10,
          max: 16,
          step: 1,
          unit: "px",
        },
        {
          key: "fontSizeLG",
          label: "Large Font Size",
          type: "number",
          description: "Large font size for emphasized text",
          min: 14,
          max: 24,
          step: 1,
          unit: "px",
        },
        {
          key: "fontSizeXL",
          label: "Extra Large Font Size",
          type: "number",
          description: "Extra large font size for headings",
          min: 18,
          max: 32,
          step: 1,
          unit: "px",
        },
        {
          key: "fontSizeHeading1",
          label: "H1 Font Size",
          type: "number",
          description: "Font size for h1 headings",
          min: 24,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "fontSizeHeading2",
          label: "H2 Font Size",
          type: "number",
          description: "Font size for h2 headings",
          min: 20,
          max: 40,
          step: 2,
          unit: "px",
        },
        {
          key: "fontSizeHeading3",
          label: "H3 Font Size",
          type: "number",
          description: "Font size for h3 headings",
          min: 16,
          max: 32,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Line Heights",
      description: "Line height settings for different text types",
      icon: "📝",
      tokens: [
        {
          key: "lineHeightLG",
          label: "Large Line Height",
          type: "number",
          description: "Line height for large text",
          min: 1,
          max: 3,
          step: 0.1,
        },
        {
          key: "lineHeightSM",
          label: "Small Line Height",
          type: "number",
          description: "Line height for small text",
          min: 1,
          max: 2.5,
          step: 0.1,
        },
        {
          key: "lineHeightHeading",
          label: "Heading Line Height",
          type: "number",
          description: "Line height for headings",
          min: 1,
          max: 2,
          step: 0.05,
        },
      ],
    },
    {
      title: "Layout & Spacing",
      description: "Layout dimensions and spacing controls",
      icon: "⚙️",
      tokens: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Default border radius for components",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "sizeUnit",
          label: "Size Unit",
          type: "number",
          description: "Base unit for component sizing calculations",
          min: 2,
          max: 8,
          step: 1,
          unit: "px",
        },
        {
          key: "sizeStep",
          label: "Size Step",
          type: "number",
          description: "Step increment for size variations",
          min: 2,
          max: 8,
          step: 1,
          unit: "px",
        },
      ],
    },
  ];

  const componentGroups: ComponentGroup[] = [
    {
      title: "Button Styles",
      description: "Customize button appearance and behavior",
      component: "Button",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of buttons",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "fontWeight",
          label: "Font Weight",
          type: "select",
          description: "Text weight of button labels",
          options: [
            { label: "Normal (400)", value: 400 },
            { label: "Medium (500)", value: 500 },
            { label: "Semi-bold (600)", value: 600 },
            { label: "Bold (700)", value: 700 },
          ],
        },
        {
          key: "controlHeight",
          label: "Default Height",
          type: "number",
          description: "Height of default size buttons",
          min: 24,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingContentHorizontal",
          label: "Horizontal Padding",
          type: "number",
          description: "Left and right padding inside buttons",
          min: 8,
          max: 32,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Input Components",
      description: "Form input styling and layout",
      component: "Input",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of input fields",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "controlHeight",
          label: "Default Height",
          type: "number",
          description: "Height of default size inputs",
          min: 24,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingContentHorizontal",
          label: "Horizontal Padding",
          type: "number",
          description: "Left and right padding inside inputs",
          min: 6,
          max: 24,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Card Components",
      description: "Card container styling and spacing",
      component: "Card",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of cards",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingLG",
          label: "Content Padding",
          type: "number",
          description: "Inner padding of card content",
          min: 8,
          max: 48,
          step: 4,
          unit: "px",
        },
        {
          key: "headerBg",
          label: "Header Background",
          type: "color",
          description: "Background color of card headers",
        },
      ],
    },
    {
      title: "Table Components",
      description: "Data table appearance and layout",
      component: "Table",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of tables",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "headerBg",
          label: "Header Background",
          type: "color",
          description: "Background color of table headers",
        },
        {
          key: "rowHoverBg",
          label: "Row Hover Color",
          type: "color",
          description: "Background color when hovering over rows",
        },
        {
          key: "headerSplitColor",
          label: "Header Border Color",
          type: "color",
          description: "Color of borders in table headers",
        },
      ],
    },
    {
      title: "Modal & Drawer",
      description: "Modal dialog and drawer panel styling",
      component: "Modal",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of modal dialogs",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingContentHorizontal",
          label: "Content Padding",
          type: "number",
          description: "Horizontal padding inside modals",
          min: 12,
          max: 48,
          step: 4,
          unit: "px",
        },
        {
          key: "paddingMD",
          label: "General Padding",
          type: "number",
          description: "General padding for modal elements",
          min: 8,
          max: 32,
          step: 4,
          unit: "px",
        },
      ],
    },
    {
      title: "Menu Components",
      description: "Navigation menu styling and spacing",
      component: "Menu",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of menu container",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "itemBorderRadius",
          label: "Item Border Radius",
          type: "number",
          description: "Corner roundness of menu items",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "itemPaddingInline",
          label: "Item Padding",
          type: "number",
          description: "Horizontal padding of menu items",
          min: 4,
          max: 24,
          step: 2,
          unit: "px",
        },
        {
          key: "itemMarginInline",
          label: "Item Margin",
          type: "number",
          description: "Horizontal margin between menu items",
          min: 0,
          max: 12,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Select Components",
      description: "Dropdown select styling and behavior",
      component: "Select",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of select components",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "controlHeight",
          label: "Default Height",
          type: "number",
          description: "Height of default size selects",
          min: 24,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "controlHeightLG",
          label: "Large Height",
          type: "number",
          description: "Height of large size selects",
          min: 32,
          max: 56,
          step: 2,
          unit: "px",
        },
        {
          key: "controlHeightSM",
          label: "Small Height",
          type: "number",
          description: "Height of small size selects",
          min: 16,
          max: 32,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Alert Components",
      description: "Alert message styling and layout",
      component: "Alert",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of alert components",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingContentHorizontal",
          label: "Horizontal Padding",
          type: "number",
          description: "Left and right padding inside alerts",
          min: 8,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingContentVertical",
          label: "Vertical Padding",
          type: "number",
          description: "Top and bottom padding inside alerts",
          min: 4,
          max: 24,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Badge Components",
      description: "Badge and status indicator styling",
      component: "Badge",
      properties: [
        {
          key: "indicatorHeight",
          label: "Indicator Height",
          type: "number",
          description: "Height of badge indicators",
          min: 12,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "indicatorHeightSM",
          label: "Small Indicator Height",
          type: "number",
          description: "Height of small badge indicators",
          min: 8,
          max: 24,
          step: 2,
          unit: "px",
        },
        {
          key: "dotSize",
          label: "Dot Size",
          type: "number",
          description: "Size of dot-style badges",
          min: 4,
          max: 16,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Tooltip & Popover",
      description: "Tooltip and popover styling",
      component: "Tooltip",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of tooltips",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingSM",
          label: "Padding",
          type: "number",
          description: "Inner padding of tooltips",
          min: 4,
          max: 20,
          step: 2,
          unit: "px",
        },
        {
          key: "fontSize",
          label: "Font Size",
          type: "number",
          description: "Text size in tooltips",
          min: 10,
          max: 16,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Notification Components",
      description: "Notification message styling",
      component: "Notification",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of notifications",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingLG",
          label: "Content Padding",
          type: "number",
          description: "Inner padding of notifications",
          min: 8,
          max: 32,
          step: 4,
          unit: "px",
        },
        {
          key: "width",
          label: "Width",
          type: "number",
          description: "Default width of notifications",
          min: 200,
          max: 500,
          step: 10,
          unit: "px",
        },
      ],
    },
    {
      title: "Message Components",
      description: "Global message styling",
      component: "Message",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of messages",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingContentHorizontal",
          label: "Horizontal Padding",
          type: "number",
          description: "Left and right padding inside messages",
          min: 8,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingContentVertical",
          label: "Vertical Padding",
          type: "number",
          description: "Top and bottom padding inside messages",
          min: 4,
          max: 24,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Drawer Components",
      description: "Side drawer panel styling",
      component: "Drawer",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of drawer panels",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingLG",
          label: "Content Padding",
          type: "number",
          description: "Inner padding of drawer content",
          min: 8,
          max: 48,
          step: 4,
          unit: "px",
        },
        {
          key: "footerPaddingBlock",
          label: "Footer Padding",
          type: "number",
          description: "Vertical padding in drawer footer",
          min: 8,
          max: 32,
          step: 4,
          unit: "px",
        },
      ],
    },
    {
      title: "Dropdown Components",
      description: "Dropdown menu styling",
      component: "Dropdown",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of dropdown menus",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingSM",
          label: "Padding",
          type: "number",
          description: "Inner padding of dropdown content",
          min: 4,
          max: 20,
          step: 2,
          unit: "px",
        },
        {
          key: "controlPaddingHorizontal",
          label: "Control Padding",
          type: "number",
          description: "Horizontal padding of dropdown controls",
          min: 6,
          max: 24,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Steps Components",
      description: "Step indicator styling",
      component: "Steps",
      properties: [
        {
          key: "iconSize",
          label: "Icon Size",
          type: "number",
          description: "Size of step icons",
          min: 16,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "iconSizeSM",
          label: "Small Icon Size",
          type: "number",
          description: "Size of small step icons",
          min: 12,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "dotSize",
          label: "Dot Size",
          type: "number",
          description: "Size of dot-style steps",
          min: 4,
          max: 16,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Progress Components",
      description: "Progress bar and circle styling",
      component: "Progress",
      properties: [
        {
          key: "defaultColor",
          label: "Default Color",
          type: "color",
          description: "Default progress bar color",
        },
        {
          key: "lineWidth",
          label: "Line Width",
          type: "number",
          description: "Thickness of progress lines",
          min: 2,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "circleTextFontSize",
          label: "Circle Text Size",
          type: "number",
          description: "Font size of text in circular progress",
          min: 10,
          max: 24,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Tag Components",
      description: "Tag and label styling",
      component: "Tag",
      properties: [
        {
          key: "borderRadiusSM",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of tags",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingInline",
          label: "Horizontal Padding",
          type: "number",
          description: "Left and right padding inside tags",
          min: 4,
          max: 20,
          step: 2,
          unit: "px",
        },
        {
          key: "paddingInlineSM",
          label: "Small Padding",
          type: "number",
          description: "Padding for small tags",
          min: 2,
          max: 16,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Tabs Components",
      description: "Tab navigation styling",
      component: "Tabs",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of tab elements",
          min: 0,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "itemPaddingSM",
          label: "Small Item Padding",
          type: "number",
          description: "Padding for small tab items",
          min: 4,
          max: 20,
          step: 2,
          unit: "px",
        },
        {
          key: "itemPaddingLG",
          label: "Large Item Padding",
          type: "number",
          description: "Padding for large tab items",
          min: 8,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "titleFontSize",
          label: "Title Font Size",
          type: "number",
          description: "Font size of tab titles",
          min: 10,
          max: 20,
          step: 1,
          unit: "px",
        },
      ],
    },
    {
      title: "Breadcrumb Components",
      description: "Breadcrumb navigation styling",
      component: "Breadcrumb",
      properties: [
        {
          key: "fontSize",
          label: "Font Size",
          type: "number",
          description: "Text size in breadcrumbs",
          min: 10,
          max: 18,
          step: 1,
          unit: "px",
        },
        {
          key: "iconFontSize",
          label: "Icon Font Size",
          type: "number",
          description: "Size of breadcrumb icons",
          min: 10,
          max: 20,
          step: 1,
          unit: "px",
        },
        {
          key: "linkColor",
          label: "Link Color",
          type: "color",
          description: "Color of breadcrumb links",
        },
        {
          key: "linkHoverColor",
          label: "Link Hover Color",
          type: "color",
          description: "Color of breadcrumb links on hover",
        },
      ],
    },
    {
      title: "Switch Components",
      description: "Toggle switch styling",
      component: "Switch",
      properties: [
        {
          key: "trackHeight",
          label: "Track Height",
          type: "number",
          description: "Height of switch track",
          min: 16,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "trackHeightSM",
          label: "Small Track Height",
          type: "number",
          description: "Height of small switch track",
          min: 12,
          max: 24,
          step: 2,
          unit: "px",
        },
        {
          key: "trackMinWidth",
          label: "Track Min Width",
          type: "number",
          description: "Minimum width of switch track",
          min: 24,
          max: 64,
          step: 4,
          unit: "px",
        },
        {
          key: "handleSize",
          label: "Handle Size",
          type: "number",
          description: "Size of switch handle",
          min: 12,
          max: 28,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Rate Components",
      description: "Star rating styling",
      component: "Rate",
      properties: [
        {
          key: "starSize",
          label: "Star Size",
          type: "number",
          description: "Size of rating stars",
          min: 12,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "starBg",
          label: "Star Background",
          type: "color",
          description: "Background color of empty stars",
        },
        {
          key: "starColor",
          label: "Star Color",
          type: "color",
          description: "Color of filled stars",
        },
        {
          key: "starHoverScale",
          label: "Hover Scale",
          type: "number",
          description: "Scale factor on star hover",
          min: 1,
          max: 1.5,
          step: 0.05,
        },
      ],
    },
    {
      title: "Checkbox Components",
      description: "Checkbox input styling",
      component: "Checkbox",
      properties: [
        {
          key: "size",
          label: "Checkbox Size",
          type: "number",
          description: "Size of checkbox control",
          min: 12,
          max: 24,
          step: 2,
          unit: "px",
        },
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of checkbox",
          min: 0,
          max: 8,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingInline",
          label: "Label Padding",
          type: "number",
          description: "Spacing between checkbox and label",
          min: 4,
          max: 16,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Radio Components",
      description: "Radio button styling",
      component: "Radio",
      properties: [
        {
          key: "size",
          label: "Radio Size",
          type: "number",
          description: "Size of radio control",
          min: 12,
          max: 24,
          step: 2,
          unit: "px",
        },
        {
          key: "dotSize",
          label: "Dot Size",
          type: "number",
          description: "Size of radio dot",
          min: 4,
          max: 12,
          step: 1,
          unit: "px",
        },
        {
          key: "paddingInline",
          label: "Label Padding",
          type: "number",
          description: "Spacing between radio and label",
          min: 4,
          max: 16,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Slider Components",
      description: "Range slider styling",
      component: "Slider",
      properties: [
        {
          key: "trackBg",
          label: "Track Background",
          type: "color",
          description: "Background color of slider track",
        },
        {
          key: "trackHeight",
          label: "Track Height",
          type: "number",
          description: "Thickness of slider track",
          min: 2,
          max: 12,
          step: 1,
          unit: "px",
        },
        {
          key: "handleSize",
          label: "Handle Size",
          type: "number",
          description: "Size of slider handle",
          min: 12,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "railBg",
          label: "Rail Background",
          type: "color",
          description: "Background color of slider rail",
        },
      ],
    },
    {
      title: "Avatar Components",
      description: "User avatar styling",
      component: "Avatar",
      properties: [
        {
          key: "borderRadius",
          label: "Border Radius",
          type: "number",
          description: "Corner roundness of avatars",
          min: 0,
          max: 50,
          step: 1,
          unit: "px",
        },
        {
          key: "containerSize",
          label: "Default Size",
          type: "number",
          description: "Default avatar size",
          min: 24,
          max: 64,
          step: 4,
          unit: "px",
        },
        {
          key: "containerSizeLG",
          label: "Large Size",
          type: "number",
          description: "Large avatar size",
          min: 32,
          max: 80,
          step: 4,
          unit: "px",
        },
        {
          key: "containerSizeSM",
          label: "Small Size",
          type: "number",
          description: "Small avatar size",
          min: 16,
          max: 48,
          step: 2,
          unit: "px",
        },
      ],
    },
    {
      title: "Typography Components",
      description: "Text and heading styling",
      component: "Typography",
      properties: [
        {
          key: "titleMarginBottom",
          label: "Title Bottom Margin",
          type: "number",
          description: "Bottom margin for titles",
          min: 4,
          max: 32,
          step: 2,
          unit: "px",
        },
        {
          key: "titleMarginTop",
          label: "Title Top Margin",
          type: "number",
          description: "Top margin for titles",
          min: 4,
          max: 48,
          step: 2,
          unit: "px",
        },
        {
          key: "titleFontWeight",
          label: "Title Font Weight",
          type: "select",
          description: "Font weight for typography titles",
          options: [
            { label: "Normal (400)", value: 400 },
            { label: "Medium (500)", value: 500 },
            { label: "Semi-bold (600)", value: 600 },
            { label: "Bold (700)", value: 700 },
          ],
        },
      ],
    },
  ];

  return {
    tokenGroups,
    componentGroups,
  };
};
